<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Str;
use Illuminate\Support\Facades\Hash;

class FacturasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('facturas')->insert([
            [
                'idVersion' => 'L15',
                'idEmisorFactura' => '12345678Z',
                'numSerieFactura' => 'F2024-0001',
                'fechaExpedicionFactura' => '20-02-2024',
                'refExterna' => 'REF123456',
                'nombreRazonEmisor' => 'Empresa S.A.',
                'subsanacion' => 'L4',
                'rechazoPrevio' => 'L17',
                'tipoFactura' => 'L2',
                'idEmisorFacturaRectificada' => '12345678X',
                'numSerieFacturaRectificada' => 'F2023-0009',
                'fechaExpedicionFacturaRectificada' => '15-12-2023',
                'idEmisorFacturaSustituida' => '87654321Y',
                'numSerieFacturaSustituida' => 'F2023-0010',
                'fechaExpedicionFacturaSustituida' => '10-11-2023',
                'baseRectificada' => 100.50,
                'cuotaRectificada' => 21.00,
                'cuotaRecargoRectificado' => 2.50,
                'fechaOperacion' => '21-02-2024',
                'descripcionOperacion' => 'Venta de productos',
                'facturaSimplificadaArt7273' => 'L4',
                'facturaSinIdentifDestinatarioArt61d' => 'L5',
                'macrodato' => 'L14',
                'emitidaPorTerceroODestinatario' => 'L6',
                'nombreRazon' => 'Cliente S.L.',
                'nif' => '8765432133X',
                'codigoPais' => 'ES',
                'idType' => 'L7',
                'id' => 'ID12345',
                'cupon' => 'L4',
                'impuesto' => 'L1',
                'claveRegimen' => 'L8A',
                'calificacionOperacion' => 'L9',
                'operacionExenta' => 'L10',
                'tipoImpositivo' => 21.00,
                'baseImponibleOimporteNoSujeto' => 150.00,
                'baseImponibleACoste' => 140.00,
                'cuotaRepercutida' => 31.50,
                'tipoRecargoEquivalencia' => 5.20,
                'cuotaRecargoEquivalencia' => 7.80,
                'cuotaTotal' => 39.30,
                'importeTotal' => 189.30,
                'primerRegistro' => '1',
                'huella' => 'huella123456',
                'fechaHoraHusoGenRegistro' => '2024-02-20T19:20:30+01:00',
                'numRegistroAcuerdoFacturacion' => 'REG001234',
                'idAcuerdoSistemaInformatico' => 'SISTEMA5678',
                'tipoHuella' => 'L12',
                'estado_proceso' => 'desbloqueada'
            ],
            [
                'idVersion' => 'L16',
                'idEmisorFactura' => '98765432A',
                'numSerieFactura' => 'F2024-0002',
                'fechaExpedicionFactura' => '22-03-2024',
                'refExterna' => 'REF654321',
                'nombreRazonEmisor' => 'SL',
                'subsanacion' => 'L5',
                'rechazoPrevio' => 'L18',
                'tipoFactura' => 'L3',
                'idEmisorFacturaRectificada' => '98765432B',
                'numSerieFacturaRectificada' => 'F2023-0011',
                'fechaExpedicionFacturaRectificada' => '16-12-2023',
                'idEmisorFacturaSustituida' => '12345678C',
                'numSerieFacturaSustituida' => 'F2023-0012',
                'fechaExpedicionFacturaSustituida' => '11-11-2023',
                'baseRectificada' => 200.00,
                'cuotaRectificada' => 42.00,
                'cuotaRecargoRectificado' => 5.00,
                'fechaOperacion' => '23-03-2024',
                'descripcionOperacion' => 'Prestación de servicios',
                'facturaSimplificadaArt7273' => 'L5',
                'facturaSinIdentifDestinatarioArt61d' => 'L6',
                'macrodato' => 'L15',
                'emitidaPorTerceroODestinatario' => 'L7',
                'nombreRazon' => 'Proveedor Uno',
                'nif' => '12345678B',
                'codigoPais' => 'PT',
                'idType' => 'L8',
                'id' => 'ID54321',
                'cupon' => 'L5',
                'impuesto' => 'L2',
                'claveRegimen' => 'L9B',
                'calificacionOperacion' => 'L10',
                'operacionExenta' => 'L11',
                'tipoImpositivo' => 10.00,
                'baseImponibleOimporteNoSujeto' => 250.00,
                'baseImponibleACoste' => 230.00,
                'cuotaRepercutida' => 25.00,
                'tipoRecargoEquivalencia' => 2.00,
                'cuotaRecargoEquivalencia' => 4.00,
                'cuotaTotal' => 29.00,
                'importeTotal' => 279.00,
                'primerRegistro' => '2',
                'huella' => 'huella654321',
                'fechaHoraHusoGenRegistro' => '2024-03-22T10:15:00+01:00',
                'numRegistroAcuerdoFacturacion' => 'REG005432',
                'idAcuerdoSistemaInformatico' => 'SISTEMA1234',
                'tipoHuella' => 'L13',
                'estado_proceso' => 'desbloqueada'
            ],
            [
                'idVersion' => 'L17',
                'idEmisorFactura' => '11223344D',
                'numSerieFactura' => 'F2024-0003',
                'fechaExpedicionFactura' => '25-04-2024',
                'refExterna' => 'REF789012',
                'nombreRazonEmisor' => 'Comercial SA',
                'subsanacion' => 'L6',
                'rechazoPrevio' => 'L19',
                'tipoFactura' => 'L4',
                'idEmisorFacturaRectificada' => '11223344E',
                'numSerieFacturaRectificada' => 'F2023-0013',
                'fechaExpedicionFacturaRectificada' => '18-12-2023',
                'idEmisorFacturaSustituida' => '22334455F',
                'numSerieFacturaSustituida' => 'F2023-0014',
                'fechaExpedicionFacturaSustituida' => '13-11-2023',
                'baseRectificada' => 300.00,
                'cuotaRectificada' => 63.00,
                'cuotaRecargoRectificado' => 7.50,
                'fechaOperacion' => '26-04-2024',
                'descripcionOperacion' => 'Compra de materiales',
                'facturaSimplificadaArt7273' => 'L6',
                'facturaSinIdentifDestinatarioArt61d' => 'L7',
                'macrodato' => 'L16',
                'emitidaPorTerceroODestinatario' => 'L8',
                'nombreRazon' => 'Cliente Dos',
                'nif' => '22334455C',
                'codigoPais' => 'FR',
                'idType' => 'L9',
                'id' => 'ID67890',
                'cupon' => 'L6',
                'impuesto' => 'L3',
                'claveRegimen' => 'L10C',
                'calificacionOperacion' => 'L11',
                'operacionExenta' => 'L12',
                'tipoImpositivo' => 15.00,
                'baseImponibleOimporteNoSujeto' => 350.00,
                'baseImponibleACoste' => 320.00,
                'cuotaRepercutida' => 52.50,
                'tipoRecargoEquivalencia' => 3.00,
                'cuotaRecargoEquivalencia' => 10.50,
                'cuotaTotal' => 63.00,
                'importeTotal' => 413.00,
                'primerRegistro' => '3',
                'huella' => 'huella789012',
                'fechaHoraHusoGenRegistro' => '2024-04-25T12:30:00+01:00',
                'numRegistroAcuerdoFacturacion' => 'REG007890',
                'idAcuerdoSistemaInformatico' => 'SISTEMA5678',
                'tipoHuella' => 'L14',
                'estado_proceso' => 'desbloqueada'
            ],

        ]);
    }
}
